### ISSUE TITLE
Vim for the Win

### ISSUE THREAD

**Issue by RobinThrift** [HannoverJS/talks#42]
###### [@RobinThrift](https://twitter.com/RobinThrift)

Vim is one of those tools you always hear of, but never dare to try. The tool of wizards with long white beards and people how only live in dark, gloomy terminals. While you might be right (to a degree), vim is one of the most powerful tools you can have in your toolbelt. It's usefulness extends merely editing a config file on a server once and then trying the next hour to close it. Vim can be, undoubtedly, the fastest way you've edited text. Ever. Every day.

**Comment by RobinThrift** [comment]
https://twitter.com/terrible_herbst/status/736237207757979648

**Comment by timche** [comment]
Is this proposal safe for the upcoming meetup on June 23? 😬

**Comment by egel** [comment]
Speaking of the topic, a while ago I wrote an article [Is worth to know the Vim Editor and why?](http://blog.egel.pl/is-worth-to-know-the-vim-editor-and-why.html) that might put some light for those who not yet knows the Vim and they are wondering if they should begin to learn it.

**Comment by egel** [comment]
I've also found interesting plugin for chrome that is called [Vimium](https://vimium.github.io/) and try to implement vim keybindings to navigate the browser. It might be fun for the audience and btw it's really great :)

**Comment by RobinThrift** [comment]
thanks for the suggestions. Those are definitely going into my 2.0 version of the talk ;)
