### ISSUE TITLE
Lightning Talk: grep/ack/ag

### ISSUE THREAD

**Issue by stphnrdmr** [HannoverJS/talks#44]
###### [@stphnrdmr](https://twitter.com/stphnrdmr)

The first of its kind: a lightning talk on searching your source!
I will show some of the functionality provided by grep/ack/ag and highlight the important differences between these rather similar tools.
When I'm done, your workflow will be better!

**Comment by timche** [comment]
Is this just a placeholder or a proposal for the upcoming meetup? 😊

**Comment by stphnrdmr** [comment]
Well, DESCRIPTION is a place holder, but June 23 as a lightning talk would work.

**Comment by timche** [comment]
Nice, we have a first lightning talk 🎉

**Comment by timche** [comment]
Added as upcoming talk :)

**Comment by timche** [comment]
Slides: https://speakerdeck.com/stphnrdmr/grep-ack-ag
