### ISSUE TITLE
Live Coding: Building a Native Mobile App with React Native

### ISSUE THREAD

**Issue by timche** [HannoverJS/talks#48]
###### [@RobinThrift](https://twitter.com/RobinThrift) & [@timche_](https://twitter.com/timche)

Not a talk, but we are going to do some live coding and build a native mobile app with React Native! What is React Native? With React Native you can build real native mobile apps using only JavaScript and it follows the same design as React to compose a rich mobile UI from declarative components.

**Comment by cburgdorf** [comment]
Super nice, wish I could be there!

Am 21.09.2016 19:30 schrieb "Tim Cheung" notifications@github.com:
