### ISSUE TITLE
Serverless Apps with AWS Lambda and Node.js

### ISSUE THREAD

**Issue by janpantel** [HannoverJS/talks#49]
###### [@JanPantel](https://twitter.com/JanPantel)

When building back ends for small to mid-size projects it quickly becomes an expensive and cumbersome task to provision servers and maintaining an infrastructure in production. In order to skip getting up in the middle of the night to fix a broken server you can build your application entirely on AWS Lambda – a service to run code without maintaining servers.

This talk will start with explaining the concepts of Lambda and how you can leverage them. Afterwards we will implement a sample app together using the ServerLess framework.

**Comment by timche** [comment]
Slides: http://slides.com/janpantel/deck
