### ISSUE TITLE
Redis for everything

### ISSUE THREAD

**Issue by omensinger** [HannoverJS/talks#50]
###### [@chocoliver](https://twitter.com/chocoliver)

We are using [redis](http://redis.io) for nearly everything at [spreadgate](http://www.spreadgate.net).
Know the basics and get inspired to use the power of redis for your next project!

**Comment by timche** [comment]
Thanks for the submission! :)

We don't have a talk for January 26 yet. Want to hold it on that date?

**Comment by omensinger** [comment]
Yes, of course!

**Comment by timche** [comment]
Great talk, thanks!
