### ISSUE TITLE
Snapshot testing in Jest

### ISSUE THREAD

**Issue by robinpokorny** [HannoverJS/talks#52]
###### [@robinpokorny](https://twitter.com/robinpokorny)

A half a year ago Jest—a testing framework from Facebook—introduced snapshot testing. This enabled developers to easily create tests for modules which possessed a challenge using traditional unit testing frameworks. For us, these included Redux reducers, actions, and most of (previously untested) React components.
Since then there have been four releases which updated and tweaked the behaviour. I will show the current possibilities with the two-days-old Jest v19.

**Comment by timche** [comment]
Thanks for submitting!

**Comment by timche** [comment]
It's set as upcoming talk for tomorrow 👍
