### ISSUE TITLE
Intro To Property Based Testing (in JavaScript)

### ISSUE THREAD

**Issue by RobinThrift** [HannoverJS/talks#55]
###### [@RobinThrift](https://twitter.com/RobinThrift)

Property based testing is a testing method often found in functional languages. If used correctly it can achieve a much greater code coverage compared to "conventional testing". Unfortunately this way of testing your functions is not widely known and often shrouded in theory heavy descriptions and jargong. I want to break it down and show you how you can test the properties of your JavaScript functions without loosing you head.

**Comment by timche** [comment]
To which date? This month? Thanks!

**Comment by RobinThrift** [comment]
@timche yep

**Comment by timche** [comment]
👍  Set as upcoming.
