### ISSUE TITLE
A RESTful IoT API build with node.js, Serverless and AWS

### ISSUE THREAD

**Issue by npohle** [HannoverJS/talks#57]
###### [@npohle](https://twitter.com/npohle)

OKLab Hannover is working on several improvements for an Air Quality IoT solution based on a hardware design that originates in Stuttgart. One of the components currently under development is a RESTful data collection API inspired by the OGC SensorThings API. The implementation makes heavy use of the Serverless Framework and is fully based on node.js.  The existing code base is far from clean but might offer some non-trivial examples for the integration with AWS Dynamo and AWS Cognito.

The talk would give a general overview of the project and discuss some of the design decisions and open challenges. Probably as a combination of overview slides and code walkthroughs. Given that the "team" behind this effort is using the project as a learning opportunity there are certainly some aspects of the current architecture and JS syntax that makes you uncomfortable and are worth a discussion ;-)

While there is some minimalistic admin frontend, the project lacks a UI so far (esp. when it comes to data visualization). So the focus here would be very much on server-side JS.

**Comment by npohle** [comment]
I'm pretty sure that I can make it to the meetup on Sep 28 but haven't prepared any slides yet. I'm always happy to improvise, however.

**Comment by timche** [comment]
Great, much thanks for your submission! Added it as upcoming talk. See you on Thursday! :)

**Comment by timche** [comment]
I had to remove the links, since we don't allow links in descriptions for security reasons. Will announce the talk today!
