### ISSUE TITLE
Building Performant API's with Koa.js 

### ISSUE THREAD

**Issue by tryshchenko** [HannoverJS/talks#61]
###### Senior JavaScript Dev @ DataArt

I couldn't say node.js back-end ecosystem is mature. It's still evolving. We have great instruments, but on the other hand, we face a lack of good practices. I have written node.js application several times before I found architecture and tooling which is clean, scalable, supportable and testable. I'd like to talk about my experience with Koa.js 2 and in particular:

- Why Koa?
- Project organization
- Architecture and patterns
- Hidden problems and frequent mistakes
- Useful tooling
- Lessons learnt

**Comment by timche** [comment]
Thanks for your submission! I'm happy to see you on January 25! 👍 :)
