### ISSUE TITLE
Learning new Languages with Exercism

### ISSUE THREAD

**Issue by nilsmartel** [HannoverJS/talks#62]
###### [@sombrastudios](https://twitter.com/sombrastudios)

I first learned about Exercism when I found their Github account (https://github.com/exercism) and taking a closer look at their website I decided to give it a try. Using Exercism might be the best way of learning a new programming language I have seen so far and I'd really like to share this with you.

Hope it's interesting enough for a (rather short) talk

**Comment by RobinThrift** [comment]
I'm looking forward to it!

**Comment by nilsmartel** [comment]
me too :)

**Comment by nilsmartel** [comment]
@RobinThrift I'm afraid you've copied the markup too directly into the hannoverJS homepage
![bildschirmfoto 2018-01-05 um 12 07 57](https://user-images.githubusercontent.com/28377948/34606813-195d39fe-f211-11e7-988e-71a056e2c282.png)

this might need to be slightly adjusted

**Comment by timche** [comment]
We don't support markdown in talk descriptions to prevent abuses. I've fixed the description by rewriting it a bit.

**Comment by nilsmartel** [comment]
Alternative way of learning languages is hackerrank.com and codewars.com !

**Comment by aforemny** [comment]
Und wenn man nur Probleme sucht https://projecteuler.net/
