### ISSUE TITLE
JSCAD : 2D/3D parametric CAD (in JavaScript)

### ISSUE THREAD

**Issue by kaosat-dev** [HannoverJS/talks#63]
###### [@kaosat_dev](https://plus.google.com/u/0/112899217323877236232)

I am one one the core developers of OpenJSCAD/JSCAD (https://github.com/jscad/OpenJSCAD.org), a set of modular, browser and command line tools for creating parametric 2D & 3D designs with JavaScript code (ie define shapes/parts by writing JS code), particularly focused on 3D printing, but also other uses. 
I would love to take you through a tour of what possibilities it offers 
* how to code designs
* the various tools/ UIs at your disposal (web, CLI, desktop)
* the perks and challenges of 3D modelling in JS
* a few 3D printed examples you can see & touch: the code is aaaliiive !

**Comment by timche** [comment]
Thanks a lot for your submission! You want to hold the talk on February 22?

**Comment by kaosat-dev** [comment]
Hi @timche ! Yes, that would be great , thanks !

**Comment by timche** [comment]
Set as upcoming talk. See you on the meetup! :)

P.S. If you want to come earlier than 6.30 pm to test your setup or having a coffee/drink beforehand, feel free to ping us.

**Comment by kaosat-dev** [comment]
Thanks :) 
I will likely take you up on the offer, thanks will confirm beforehand!

**Comment by timche** [comment]
The meetup will start at 6.30 pm with drinks and pizza following with talks at 7 pm.
