### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by mxmzb** [HannoverJS/talks#67]
###### [@mxmzb](https://www.twitter.com/mxmzb)

- What's GraphQL?
- Why not REST?
- Who is using GraphQL already and in which way?
- Client and server side.
- Pros and cons.
- Frameworks.
- Maybe: Small "hands on" presentation?

**Comment by mxmzb** [comment]
https://github.com/HannoverJS/talks/issues/59

**Comment by timche** [comment]
Sehr cool! Danke!

**Comment by timche** [comment]
Cool, thanks! Could you please use English?

**Comment by mxmzb** [comment]
You're welcome :) You mean here, in the presentation or both? Sure thing in any case though :)

**Comment by timche** [comment]
Talk description (top) only. Talk and slides can be in German.

**Comment by timche** [comment]
Want to hold the talk on May 26?

**Comment by mxmzb** [comment]
yes please!

**Comment by maxrimue** [comment]
Hey @mxmzb, unfortunately we will have to reschedule the meetup for the 30th of May. Is that ok with you?

**Comment by mxmzb** [comment]
@maxrimue sure!

**Comment by maxrimue** [comment]
Thanks again for the awesome talk!
