### ISSUE TITLE
WebAssembly – The Impractical Guide

### ISSUE THREAD

**Issue by RobinThrift** [HannoverJS/talks#68]
###### [@RobinThrift](https://twitter.com/RobinThrift)

You may have heard of wasm being the hot new thing. It will solve many problems we face in modern front end development, and thus has many practical applications. You may be excited to use it. Well this talk will not help you with that, but what it will do is teach you how to write WebAssembly by hand (yes, I mean hex code) and other useless details you never knew you didn't want to know.

**Comment by maxrimue** [comment]
@RobinThrift The meetup has been rescheduled to the 30th of May, is that ok with you? 
Also, could you add an occupation? I've inserted a placeholder `/` for the time being, because leaving it out breaks the component on hannoverjs.de 😬
