### ISSUE TITLE
Snabbdom: A lightweight virtual DOM library

### ISSUE THREAD

**Issue by kay999** [HannoverJS/talks#74]
###### Freelance full-stack developer 

Snabbdom is a lightweight virtual DOM library which is used in frameworks like Vue.js and Cycle.js as the DOM renderer.

But with under 4KB size (gzipped+minified) and a highly modular structure, Snabbdom is also very useful for building small (and not so small) dynamic web UI components without committing to a framework. 

The talk will demonstrate how Snabbdom works and how to build simple UI components with it "functional style".

**Comment by RobinThrift** [comment]
Is it okay if I schedule this for this month (April)?

**Comment by kay999** [comment]
Yes, I can do it next meetup.
