### ISSUE TITLE
Schematics Workshop

### ISSUE THREAD

**Issue by ngfelixl** [HannoverJS/talks#75]
###### [@ngfelixl](https://twitter.com/ngfelixl)

The talk is about understanding schematics and the abstract syntax tree (AST) and writing custom schematics. In the beginning you will get an introduction to schematics and while continuing we are going to improve and add more skills/tasks. I will provide further resources and guidance for get going afterwards. The workshop will take 90m, divided into the following sections:

- Introduction and getting started (workspace setup, first schematic, exercises) (20m)
- Improve (working with template files, understanding the AST, exercises) (20m)
- Angular workspace (sandbox, utility-hell, getting/writing information from/to an ng-workspace, exercises) (30m)
- Add ng-add and ng-update support (5m)
- Testing (write unit tests for your schematic, create test angular workspace, exercises) (15m)

Attendees will need a PC/Mac with Nodejs and NPM preinstalled.

**Comment by ngfelixl** [comment]
I will not be available next week (May), but June or July would be fine.

**Comment by RobinThrift** [comment]
Ah, what a shame, I was just about to ask about that 😅
But we'd be happy to schedule you for June!

**Comment by ngfelixl** [comment]
Ups, I am sorry for that. 😱 June would be great! Thank you very much.

**Comment by RobinThrift** [comment]
Don't worry about it 😄
We're looking forward to hosting you in June!
