### ISSUE TITLE
Parcel: A magical bundler with little good use

### ISSUE THREAD

**Issue by kytta** [HannoverJS/talks#78]
###### [@NickKaramoff](https://twitter.com/NickKaramoff)

I'll talk about Parcel, a totally magical JavaScript file bundler: about how great it is and about how you might *not* want to use it.

**Comment by kytta** [comment]
I'd like to convey this talk on 26.11.2019

I also have a question: should the talk be in English or German? I mean my speech as well as the text on the slides.

**Comment by RobinThrift** [comment]
Yes, we'd love to have you on the 26.11.!
Most speakers generally write their slides in English and hold the talk in German, but we are flexible and make it completely up to the speaker to decide, either is fine with us.

I will set the labels and your talk will appear as scheduled within the next 24h on the website!

**Comment by kytta** [comment]
Vielen Dank an die Gäste und die Organisatoren! Die Folien kann man hier finden:
—
Huge thanks to all the guests and the organizers! The slides are now available here:

https://s.karamoff.ru/parcel-talk
